name: carlog
description: A vehicle log app for tracking maintenance, repairs, fuel, and car info.
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Networking & JSON
  http: ^1.2.0

  # UI / Navigation
  cupertino_icons: ^1.0.8
  flutter_spinkit: ^5.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
